title: 今日の空もよう
markdown: kramdown
timezone: Asia/Tokyo
author: Koyama Hiromi
url: "https://koyuhi.github.io"
baseurl: "/kyou-no-sora"
exclude:
  - node_modules
  - README.md
  - .sass-cache
  - Gemfile
  - Gemfile.lock
